### ISSUE TITLE
CompositeETHPriceFeed support for WBTC

### ISSUE THREAD

**Issue by yaronvel** [Gearbox-protocol/core-v2#15]
We plan to suggest the community to use a WBTC price oracle that compose BTC/USD and WBTC/BTC prices.
This is very much in favour to how the current stETH price is implemented.

On first look it seems that the code could be used as is, but a review is needed, and one might consider to change the variable names in order to make it more generic.

**Comment by 0xmikko** [comment]
Sounds reasonable, it would not increase gas costs dramatically and would create additional protection in case of depeg.
