### ISSUE TITLE
Liquidation that breaks the cumulative loss limit will revert if credit manager is paused

### ISSUE THREAD

**Issue by lekhovitsky** [Gearbox-protocol/core-v2#68]
Once cumulative loss from liquidation breaks the limit, the credit facade tries to pause the credit manager:
https://github.com/Gearbox-protocol/core-v2/blob/98a984d37fa590e89ff976fe9e2a523b217d50ef/contracts/credit/CreditFacade.sol#L617-L625

The issue with this is that underlying `Pausable` implementation doesn't allow to pause an already paused contract: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ecd2ca2cd7cac116f7a37d0e474bbb3d7d5e1c4d/contracts/security/Pausable.sol#L89

This issue is fixed in V3: https://github.com/Gearbox-protocol/core-v3/blob/main/contracts/credit/CreditFacadeV3.sol#L338-L346

**Comment by Van0k** [comment]
This is valid, but the issue is not severe enough to warrant Credit Facade redeployment. The current state of the contracts is manageable.
